# Generated by Django 4.2.5 on 2024-01-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('idcontactrequest', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contactrequest',
                'managed': False,
            },
        ),
    ]
