# Generated by Django 4.2.5 on 2023-11-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FUGTApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointInteret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="SortiePlanifiee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "points_interet",
                    models.ManyToManyField(
                        related_name="sorties_planifiees", to="FUGTApp.pointinteret"
                    ),
                ),
            ],
        ),
    ]
