# Generated by Django 4.2.5 on 2023-12-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('id_activite', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
