# Generated by Django 4.2.5 on 2023-12-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0002_activitereservation_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitereservation',
            table='activite_reservation',
        ),
    ]
