# Generated by Django 4.2.5 on 2023-11-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0002_activite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'managed': False},
        ),
    ]
