# Generated by Django 4.2.5 on 2024-01-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0002_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FUGTApp.activite')),
            ],
        ),
    ]
