# Generated by Django 4.2.5 on 2023-11-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0003_alter_activite_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activite',
            table='activite',
        ),
    ]
