# Generated by Django 4.2.5 on 2024-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0003_whatsappchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsappchanel',
            fields=[
                ('idwhatsappchanel', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=45)),
                ('activiteid', models.IntegerField()),
            ],
            options={
                'db_table': 'whatsappchanel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WhatsAppChannel',
        ),
    ]
