# Generated by Django 5.0 on 2023-12-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0002_pointinteret_sortieplanifiee'),
        ('FUGTApp', '0004_alter_activite_table'),
    ]

    operations = [
    ]
