# Generated by Django 4.2.5 on 2024-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0004_whatsappchanel_delete_whatsappchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackimage',
            fields=[
                ('idfeedbackimage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activite_images/')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True)),
                ('id_activite', models.IntegerField()),
            ],
            options={
                'db_table': 'feedbackimage',
                'managed': False,
            },
        ),
    ]
