# Generated by Django 5.0 on 2023-12-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUGTApp', '0005_merge_20231205_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sortieplanifiee',
            name='points_interet',
        ),
        migrations.DeleteModel(
            name='PointInteret',
        ),
        migrations.DeleteModel(
            name='SortiePlanifiee',
        ),
    ]
