name: 'fugt backend ci'

on:
  push:
    paths:
      - 'FUGTSite/**'
      - '.github/workflows/backend-ci.yml'

# Set default working directory to backend directory
defaults:
  run:
    working-directory: './FUGTSite'

jobs:
  build:
    runs-on: ubuntu-latest

    # checkout the code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Run tests
        run: python manage.py test




