name: 'fugt backend ci'

on:
  push:
    paths:
      - 'FUGTSite/**'
      - '.github/workflows/backend-ci.yml'

# Set default working directory to backend directory
defaults:
  run:
    working-directory: './FUGTSite'

jobs:
  build:
    runs-on: ubuntu-latest

    # checkout the code
    steps:
      - uses: actions/checkout@v4

      # set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: run tests
        run: python manage.py test




