name: fugt backend ci

on:
  push:
    paths:
      - 'FUGTSite/**'
      - '.github/workflows/backend-ci.yml'

defaults:
  run:
    working-directory: './FUGTSite'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear Python cache
        run: |
          rm -rf $RUNNER_TOOL_CACHE/Python*

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test --verbosity=3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fugt-backend:latest

      - name: Run Docker container
        run: docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fugt-backend:latest
