name: 'fugt backend ci'

on:
  push:
    paths:
      - 'FUGTSite/**'
      - '.github/workflows/backend-ci.yml'

# Set default working directory to backend directory
defaults:
  run:
    working-directory: './FUGTSite'

jobs:
  build:
    runs-on: ubuntu-latest

    # checkout the code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear Python cache
        run: |
          rm -rf $RUNNER_TOOL_CACHE/Python*

      # set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codeclimate-test-reporter

      - name: Activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Run Tests and Coverage
        run: |
          codeclimate-test-reporter coverage run -m pytest
          codeclimate-test-reporter

      - name: Run tests
        run: python manage.py test
        
        env:
          CI: true
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}




