name: fugt react ci

on:
  push:
    paths:
      - 'fugtreact/**'
      - '.github/workflows/react-ci.yml'

defaults:
  run:
    working-directory: './fugtreact'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-coverage-report
          path: coverage/lcov.info

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fugt/fugt-frontend:latest

      - name: Run Docker container
        run: docker run -d -p 3000:3000 fugt/fugt-frontend:latest
