name: 'fugt react ci'

on:
  push:
    paths:
      - 'fugtreact/**'
      - '.github/workflows/react-ci.yml'


# Set default working directory to react directory
defaults:
  run:
    working-directory: './fugtreact'

jobs:
  build:
    runs-on: ubuntu-latest

    # checkout the code
    steps:
      - uses: actions/checkout@v4

      # name: install dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-coverage-report
          path: coverage/lcov.info
          
      - name: build
        run: npm run build







