name: 'fugt react ci'

on:
  push:
    paths:
      - 'fugtreact/**'
      - '.github/workflows/react-ci.yml'


# Set default working directory to react directory
defaults:
  run:
    working-directory: './fugtreact'

jobs:
  build:
    runs-on: ubuntu-latest

    # checkout the code
    steps:
      - uses: actions/checkout@v4

      # name: install dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test -- --coverage
          coverageLocations: "coverage/lcov.info:lcov"

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Download Code Climate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Upload coverage to Code Climate
        run: |
          ./cc-test-reporter before-build
          ./cc-test-reporter after-build --exit-code $? --id ${{ secrets.CC_TEST_REPORTER_ID }} --coverage-input-type lcov --xml-report coverage/lcov.info
          
      - name: build
        run: npm run build







